blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/qrjhamron/ApexSU/discussions
    about: "Please use Discussions for feature proposals and design feedback."
